//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPath.LGAIResearch.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPath.LGAIResearch.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Key for Deep Document Understanding.
        /// </summary>
        public static string AnalyzeDocument_ApiKey_Description {
            get {
                return ResourceManager.GetString("AnalyzeDocument_ApiKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApiKey.
        /// </summary>
        public static string AnalyzeDocument_ApiKey_DisplayName {
            get {
                return ResourceManager.GetString("AnalyzeDocument_ApiKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze input document .
        /// </summary>
        public static string AnalyzeDocument_Description {
            get {
                return ResourceManager.GetString("AnalyzeDocument_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalyzeDocument.
        /// </summary>
        public static string AnalyzeDocument_DisplayName {
            get {
                return ResourceManager.GetString("AnalyzeDocument_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint for LGAI Deep Document Understanding .
        /// </summary>
        public static string AnalyzeDocument_Endpoint_Description {
            get {
                return ResourceManager.GetString("AnalyzeDocument_Endpoint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint.
        /// </summary>
        public static string AnalyzeDocument_Endpoint_DisplayName {
            get {
                return ResourceManager.GetString("AnalyzeDocument_Endpoint_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response error description .
        /// </summary>
        public static string AnalyzeDocument_ErrorStatus_Description {
            get {
                return ResourceManager.GetString("AnalyzeDocument_ErrorStatus_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Status &amp; message .
        /// </summary>
        public static string AnalyzeDocument_ErrorStatus_DisplayName {
            get {
                return ResourceManager.GetString("AnalyzeDocument_ErrorStatus_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated time for result.
        /// </summary>
        public static string AnalyzeDocument_EstimatedTime_Description {
            get {
                return ResourceManager.GetString("AnalyzeDocument_EstimatedTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EstimatedTIme.
        /// </summary>
        public static string AnalyzeDocument_EstimatedTime_DisplayName {
            get {
                return ResourceManager.GetString("AnalyzeDocument_EstimatedTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filepath for input documents (pdf, jpg, pgn supported).
        /// </summary>
        public static string AnalyzeDocument_FilePath_Description {
            get {
                return ResourceManager.GetString("AnalyzeDocument_FilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilePath.
        /// </summary>
        public static string AnalyzeDocument_FilePath_DisplayName {
            get {
                return ResourceManager.GetString("AnalyzeDocument_FilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of detected molecule .
        /// </summary>
        public static string AnalyzeDocument_Molecules_Description {
            get {
                return ResourceManager.GetString("AnalyzeDocument_Molecules_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moleculars.
        /// </summary>
        public static string AnalyzeDocument_Molecules_DisplayName {
            get {
                return ResourceManager.GetString("AnalyzeDocument_Molecules_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id for document analysis request.
        /// </summary>
        public static string AnalyzeDocument_RequestId_Description {
            get {
                return ResourceManager.GetString("AnalyzeDocument_RequestId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestId.
        /// </summary>
        public static string AnalyzeDocument_RequestId_DisplayName {
            get {
                return ResourceManager.GetString("AnalyzeDocument_RequestId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApiKey for EXAONE LLM .
        /// </summary>
        public static string GenerateContent_ApiKey_Description {
            get {
                return ResourceManager.GetString("GenerateContent_ApiKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApiKey.
        /// </summary>
        public static string GenerateContent_ApiKey_DisplayName {
            get {
                return ResourceManager.GetString("GenerateContent_ApiKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Chat completion with EXAONE LLM .
        /// </summary>
        public static string GenerateContent_Description {
            get {
                return ResourceManager.GetString("GenerateContent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Generation.
        /// </summary>
        public static string GenerateContent_DisplayName {
            get {
                return ResourceManager.GetString("GenerateContent_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint for EXAONE LLM.
        /// </summary>
        public static string GenerateContent_Endpoint_Description {
            get {
                return ResourceManager.GetString("GenerateContent_Endpoint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint.
        /// </summary>
        public static string GenerateContent_Endpoint_DisplayName {
            get {
                return ResourceManager.GetString("GenerateContent_Endpoint_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of max new token for EXAONE ( default 1024 max 4096).
        /// </summary>
        public static string GenerateContent_MaxNewToken_Description {
            get {
                return ResourceManager.GetString("GenerateContent_MaxNewToken_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxNewToken.
        /// </summary>
        public static string GenerateContent_MaxNewToken_DisplayName {
            get {
                return ResourceManager.GetString("GenerateContent_MaxNewToken_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat completion response .
        /// </summary>
        public static string GenerateContent_Response_Description {
            get {
                return ResourceManager.GetString("GenerateContent_Response_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string GenerateContent_Response_DisplayName {
            get {
                return ResourceManager.GetString("GenerateContent_Response_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System prompt for EXAONE LLM.
        /// </summary>
        public static string GenerateContent_SystemPrompt_Description {
            get {
                return ResourceManager.GetString("GenerateContent_SystemPrompt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemPrompt.
        /// </summary>
        public static string GenerateContent_SystemPrompt_DisplayName {
            get {
                return ResourceManager.GetString("GenerateContent_SystemPrompt_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature for EXAONE range from 0 to 1 (default 0.1).
        /// </summary>
        public static string GenerateContent_Temperature_Description {
            get {
                return ResourceManager.GetString("GenerateContent_Temperature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string GenerateContent_Temperature_DisplayName {
            get {
                return ResourceManager.GetString("GenerateContent_Temperature_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top K for EXAONE (default 50).
        /// </summary>
        public static string GenerateContent_TopK_Description {
            get {
                return ResourceManager.GetString("GenerateContent_TopK_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopK.
        /// </summary>
        public static string GenerateContent_TopK_DisplayName {
            get {
                return ResourceManager.GetString("GenerateContent_TopK_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Probability for EXAONE (default 1).
        /// </summary>
        public static string GenerateContent_TopP_Description {
            get {
                return ResourceManager.GetString("GenerateContent_TopP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopP.
        /// </summary>
        public static string GenerateContent_TopP_DisplayName {
            get {
                return ResourceManager.GetString("GenerateContent_TopP_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User promprt for content generation with EXAONE LLM.
        /// </summary>
        public static string GenerateContent_UserPrompt_Description {
            get {
                return ResourceManager.GetString("GenerateContent_UserPrompt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPrompt.
        /// </summary>
        public static string GenerateContent_UserPrompt_DisplayName {
            get {
                return ResourceManager.GetString("GenerateContent_UserPrompt_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate SVG from smiles.
        /// </summary>
        public static string GenerateSVGFromSmiles_Description {
            get {
                return ResourceManager.GetString("GenerateSVGFromSmiles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateSVGFromSmiles.
        /// </summary>
        public static string GenerateSVGFromSmiles_DisplayName {
            get {
                return ResourceManager.GetString("GenerateSVGFromSmiles_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint for SVG generation.
        /// </summary>
        public static string GenerateSVGFromSmiles_Endpoint_Description {
            get {
                return ResourceManager.GetString("GenerateSVGFromSmiles_Endpoint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint.
        /// </summary>
        public static string GenerateSVGFromSmiles_Endpoint_DisplayName {
            get {
                return ResourceManager.GetString("GenerateSVGFromSmiles_Endpoint_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smiles (base64 format).
        /// </summary>
        public static string GenerateSVGFromSmiles_Smiles_Description {
            get {
                return ResourceManager.GetString("GenerateSVGFromSmiles_Smiles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smiles.
        /// </summary>
        public static string GenerateSVGFromSmiles_Smiles_DisplayName {
            get {
                return ResourceManager.GetString("GenerateSVGFromSmiles_Smiles_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated SVG file path.
        /// </summary>
        public static string GenerateSVGFromSmiles_SvgPath_Description {
            get {
                return ResourceManager.GetString("GenerateSVGFromSmiles_SvgPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SvgPath.
        /// </summary>
        public static string GenerateSVGFromSmiles_SvgPath_DisplayName {
            get {
                return ResourceManager.GetString("GenerateSVGFromSmiles_SvgPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LGAI DDU model Api Key.
        /// </summary>
        public static string GetResult_ApiKey_Description {
            get {
                return ResourceManager.GetString("GetResult_ApiKey_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApiKey.
        /// </summary>
        public static string GetResult_ApiKey_DisplayName {
            get {
                return ResourceManager.GetString("GetResult_ApiKey_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted Document Elements Information .
        /// </summary>
        public static string GetResult_DDUData_Description {
            get {
                return ResourceManager.GetString("GetResult_DDUData_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moleculars.
        /// </summary>
        public static string GetResult_DDUData_DisplayName {
            get {
                return ResourceManager.GetString("GetResult_DDUData_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrive results for AnalyzeDocument.
        /// </summary>
        public static string GetResult_Description {
            get {
                return ResourceManager.GetString("GetResult_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get DDU Result.
        /// </summary>
        public static string GetResult_DisplayName {
            get {
                return ResourceManager.GetString("GetResult_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LGAI DDU model endpoint .
        /// </summary>
        public static string GetResult_Endpoint_Description {
            get {
                return ResourceManager.GetString("GetResult_Endpoint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint.
        /// </summary>
        public static string GetResult_Endpoint_DisplayName {
            get {
                return ResourceManager.GetString("GetResult_Endpoint_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message .
        /// </summary>
        public static string GetResult_ErrorMessage_Description {
            get {
                return ResourceManager.GetString("GetResult_ErrorMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        public static string GetResult_ErrorMessage_DisplayName {
            get {
                return ResourceManager.GetString("GetResult_ErrorMessage_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result of LGAI DDU Analyze Document Activity .
        /// </summary>
        public static string GetResult_RequestId_Description {
            get {
                return ResourceManager.GetString("GetResult_RequestId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestId.
        /// </summary>
        public static string GetResult_RequestId_DisplayName {
            get {
                return ResourceManager.GetString("GetResult_RequestId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
